/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'koopa' at '1/22/17 8:32 PM' with Gradle 3.0
 *
 * @author koopa, @date 1/22/17 8:32 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
